version = 5.5.0
archive_dir = /etc/letsencrypt/archive/student.duadata.net
cert = /etc/letsencrypt/live/student.duadata.net/cert.pem
privkey = /etc/letsencrypt/live/student.duadata.net/privkey.pem
chain = /etc/letsencrypt/live/student.duadata.net/chain.pem
fullchain = /etc/letsencrypt/live/student.duadata.net/fullchain.pem
[renewalparams]
account = b66f550db2b2e8b196123e472cdd1396
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
student.duadata.net = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-07-05T20:06:43
